### ISSUE TITLE
Tratar mensagens com foto

### ISSUE THREAD

**Issue by caburu** [ufla-ppoo/RedeSocialGrafica#10]
Um dos grandes "problemas" do código de exemplo da rede social usando terminal é que a mensagem com foto não permite exibir a foto. Chamaria bem a atenção aqui se fosse possível postar mensagens com foto.

**Comment by Vidaflor111** [comment]
Ola!
Gostaria de trabalhar nessa Issue.

**Comment by caburu** [comment]
Olá @Vidaflor111, bacana que está disposta a colaborar!

A ideia é fazer algo bem simples. Poderia ser, por exemplo, através de um novo botão que, ao ser clicado, pedisse para o usuário o ID da mensagem a ser visualizada e, se fosse uma mensagem com foto, exibisse a imagem.

Como é um projeto bem simples, não há um procedimento formal para contribuições. Mas, para mantermos as coisas organizadas, seria bom que enviasse a solução da issue na forma de um Pull Request para que eu possa comentar/avaliar a solução.

Qualquer dúvida adicional quanto ao projeto ou à issue em si, estou à disposição.

**Comment by caburu** [comment]
Resolvido em #14
