### ISSUE TITLE
Passo para tratar erro com `Integer.parseInt`

### ISSUE THREAD

**Issue by caburu** [ufla-ppoo/RedeSocialGrafica#12]
O código fornecido pede ao usuário o id da mensagem usando o método `JOptionPane.showInputDialog`, e o retorno desse método é passado diretamente como parâmetro para o método `Integer.parseInt`.

Com isso, se o usuário digita uma string que não pode ser convertida para inteiro, ou se não digita nada, ou ainda se clica em cancelar, ocorre uma exceção do tipo `NumberFormatException`.

Talvez fosse interessante acrescentar um passo sobre isso (avaliar se opcional ou não).

**Comment by natharaujos** [comment]
Olá, gostaria de trabalhar nesta issue.

**Comment by caburu** [comment]
Olá @natharaujos, bacana que está disposto a colaborar!

A ideia é criar um novo exercício, alterando o arquivo README.md. Esse exercício poderia ser depois do Passo 2.3. A ideia é escrever o enunciado descrevendo a situação que mencionei nessa issue e pedindo o aluno para tratá-la.

Como é um projeto bem simples, não há um procedimento formal para contribuições. Mas, para mantermos as coisas organizadas, seria bom que enviasse a solução da issue na forma de um Pull Request para que eu possa comentar/avaliar a solução.

Qualquer dúvida quanto ao projeto ou à issue em si, estou à disposição.

**Comment by caburu** [comment]
Resolvido no commit 577274b5471b9edf7f5ae6cf6240af408efedd9e
