### ISSUE TITLE
Explicar melhor Passo 1.3 (uso do `JScrollPane`)

### ISSUE THREAD

**Issue by caburu** [ufla-ppoo/RedeSocialGrafica#4]
O enunciado atual do Passo 1.3 gerou muitas dúvidas para os alunos.

Seria interessante deixar mais claro o funcionamento do componente:
- Que ele acrescenta uma funcionalidade ao componente `JTextArea`.
- E que ele acaba funcionando como uma camada intermediária entre o `JPanel` e o `JTextArea`.

Além disso, seria interessante orientar sobre como testar a implementação (redimensionar a janela, por exemplo, é mais prático para testar do que ter que publicar 10 mensagens).

**Comment by jeliasppoo** [comment]
Professor, 
Ao dizer componete vc faze referência a que? 
A ideia e criar um objeto da classe  "JScrollPane" na Função "criarComponentes()" ? Estou confuso quando você diz "para adicionar o JScrollPane na janela **ao invez do componete do feed**".

**Comment by caburu** [comment]
Olá Elias, me refiro ao componente que exibe o texto do Feed de Notícias, ou seja, o atributo `areaTextoFeed` que é do tipo `JTextArea`.
- O objeto do tipo `JScrollPane` deve ser criado passando o `areaTextoFeed` como parâmetro.
- E depois objeto do tipo `JScrollPane` deve ser adicionado ao painel, em vez do  `areaTextoFeed`.
